# ~/.config/starship.toml

# Purpose: HomeSetup's starship configuration file.
# Created: Aug 26, 2018
#  Author: <B>H</B>ugo <B>S</B>aporetti <B>J</B>unior
#  Mailto: homesetup@gmail.com
#    Site: https://github.com/yorevs/homesetup
#
# See a the full starship reference at: https://starship.rs/config/#prompt

# Timeout for starship to scan files (in milliseconds).
scan_timeout = 10

# Disable the blank line at the start of the prompt.
add_newline = false

# Continuation prompt (PS2).
continuation_prompt = "... "

# Set "homesetup" as custom color palette.
palette = "homesetup"

# Format the prompt
format = "${os} ${custom.history} ${username} ${hostname} ${directory} ${git_branch} ${git_status}${character}"


[line_break]
disabled = true


# Define custom colors from: https://i.stack.imgur.com/KTSQa.png
[palettes.homesetup]
blue = "27"
cyan = "14"
purple = "56"
green = "2"
orange = "202"
red = "9"


[custom.history]
shell = "bash"
command = "grep -v '^#' ${HOME}/.bash_history | wc -l | sed -r 's/ *//'"
when = "true"
style = "white"
format = '[\(${output}\)](${style})'
disabled = false


[os]
style = "white"
format = "[${symbol}](${style})"
disabled = false


[os.symbols]
Linux = ""
Macos = ""
CentOS = ""
Fedora = ""
Ubuntu = ""


[username]
style_user = "green"
style_root = "red"
format = "[ $user](${style})"
show_always = true
disabled = false


[hostname]
ssh_only = false
ssh_symbol = ""
format = "[${ssh_symbol} ${hostname}](purple)"
disabled = false


[directory]
style = "orange"
format = "[  ${path}](${style})"
disabled = false


[git_branch]
symbol = " "
style = "cyan"
format = "[${symbol}${branch}](${style})"
disabled = false


[git_status]
style = "cyan"

[character]
success_symbol = "[](white)"
error_symbol = "[](white)"


[gradle]
disabled = true


[java]
disabled = true
