# ~/.config/starship.toml

# Purpose: HomeSetup's starship configuration file.
# Created: Aug 26, 2018
#  Author: <B>H</B>ugo <B>S</B>aporetti <B>J</B>unior
#  Mailto: homesetup@gmail.com
#    Site: https://github.com/yorevs/homesetup
#
# See a the full starship reference at: https://starship.rs/config/#prompt

# Timeout for starship to scan files (in milliseconds).
scan_timeout = 20

# Disable the blank line at the start of the prompt.
add_newline = false

# Continuation prompt (PS2).
continuation_prompt = "… "

# Set "homesetup" as custom color palette.
palette = "homesetup"

# Format the prompt.
format = "${os}${custom.history}${username}${hostname}${directory}${git_branch}${git_status}${character}"

# Define custom colors from: https://i.stack.imgur.com/KTSQa.png
[palettes.homesetup]
blue = "27"
cyan = "14"
purple = "56"
green = "2"
orange = "202"
red = "9"

# Print the history size.
[custom.history]
shell = "bash"
command = "grep -v '^#' ${HOME}/.bash_history | wc -l | sed -r 's/ *//'"
when = "true"
style = "white"
format = '[\(${output}\)](${style}) '
disabled = false

[os]
style = "bold white"
format = "[${symbol}](${style}) "
disabled = false

[os.symbols]
Linux = ""
Macos = ""
CentOS = ""
Fedora = ""
Ubuntu = ""
Alpine = ""

[username]
style_user = "green"
style_root = "red"
format = "[[](bold white) $user](${style}) "
show_always = true
disabled = false

[hostname]
ssh_only = false
ssh_symbol = " :"
trim_at = "."
format = "[[${ssh_symbol}](bold white) ${hostname}](purple) "
disabled = false

[directory]
style = "orange"
format = "[[](bold white) ${path}](${style}) "
truncation_length = 3
truncate_to_repo = true
truncation_symbol = ' …/'
disabled = false

[git_branch]
symbol = " "
style = "cyan"
format = "[[${symbol}](bold white)${branch}](${style}) "
disabled = false

[git_status]
style = "cyan"
format = '[(\[$all_status\][$behind$ahead](red) )]($style)'

[character]
success_symbol = "[](bold white)"
error_symbol = "[](bold white)"

#### Disabled modules ####

[hg_branch]
disabled = true

[dart]
disabled = true

[dotnet]
disabled = true

[elixir]
disabled = true

[elm]
disabled = true

[erlang]
disabled = true

[golang]
disabled = true

[helm]
disabled = true

[java]
disabled = true

[julia]
disabled = true

[kotlin]
disabled = true

[nim]
disabled = true

[ocaml]
disabled = true

[php]
disabled = true

[purescript]
disabled = true

[swift]
disabled = true

[zig]
disabled = true

[memory_usage]
disabled = true

[gcloud]
disabled = true

[openstack]
disabled = true

[crystal]
disabled = true

[lua]
disabled = true

[jobs]
disabled = true

[battery]
disabled = true
