# HomeSetup github-pages configuration
remote_theme: pages-themes/leap-day@v0.2.0

plugins:
- jekyll-remote-theme

title: HomeSetup
description: The ultimate Terminal experience

show_downloads: "true"

author: Hugo Saporetti Junior

blank_issues_enabled: false

contact_links:
  - name: HomeSetup Support
    url: https://gitter.im/yorevs-homesetup/community/
    about: Please ask and answer questions here.
