# HomeSetup github-pages configuration
theme: jekyll-theme-slate
plugins:
- jekyll-remote-theme


url: https://yorevs.github.io
baseurl: /homesetup
show_downloads: "true"
blank_issues_enabled: false

title: HomeSetup
description: > # The ultimate Terminal experience
  HomeSetup simplifies terminal customization by offering seamless cloud
  integration for dotfiles, packages, and configurations, enhancing productivity
  and command line experiences without complex frameworks.

author: Hugo Saporetti Junior
email: taius.hhs@gmail.com

# Contact links
contact_links:
  - name: Support
    url: https://gitter.im/yorevs-homesetup/community/
    about: Please ask and answer questions here.

# social links
github_username:  yorevs
show_excerpts: true
