#!/usr/bin/env bats

#  Script: hhs-text.bats
# Purpose: hhs-text tests.
# Created: Feb 16, 2025
#  Author: Generated by ChatGPT (gpt-5-codex)
# License: Please refer to <https://opensource.org/licenses/MIT>
#

load test_helper
load "${HHS_FUNCTIONS_DIR}/hhs-text.bash"
load_bats_libs

# TC - 1
@test "when-highlighting-text-from-file-then-matching-line-is-colored" {
  local input_file
  input_file="${BATS_TEST_TMPDIR}/highlight.txt"

  cat <<'EOF' >"${input_file}"
alpha
Beta
gamma
EOF

  run __hhs_highlight "beta" "${input_file}"

  assert_success
  assert_output --partial $'\e['
  assert_output --partial 'Beta'
  refute_output --partial 'alpha'
  refute_output --partial 'gamma'
}

# TC - 2
@test "when-jq-is-available-then-json-print-uses-it" {
  local stub_dir
  stub_dir="${BATS_TEST_TMPDIR}/stubs"
  mkdir -p "${stub_dir}"

  cat <<'EOF' >"${stub_dir}/jq"
#!/usr/bin/env bash
python3 - "$@" <<'PYTHON'
import json
import sys

data = json.loads(sys.stdin.read())
print(json.dumps(data, indent=2, sort_keys=True))
PYTHON
EOF

  chmod +x "${stub_dir}/jq"

  run env PATH="${stub_dir}:${PATH}" __hhs_json_print '{"foo": 1, "bar": 2}'

  assert_success
  assert_output --partial '"bar": 2'
  assert_output --partial '"foo": 1'
}

# TC - 3
@test "when-converting-string-to-ascii-then-numeric-representations-are-returned" {
  run __hhs_ascof 'Hi'

  assert_success
  assert_output --partial $'Dec: 72 105'
  assert_output --partial $'Hex: 48 69'
  assert_output --partial 'Str: Hi'
}

# TC - 4
@test "when-converting-valid-unicode-then-all-representations-are-printed" {
  run __hhs_utoh f123

  assert_success
  assert_output --partial "[Unicode:'\\uf123']"
  assert_output --partial 'Hex => \xef\x84\xa3'
  assert_output --partial 'Icn => '
  assert_output --partial 'Oct => \357\204\243'
}

# TC - 5
@test "when-python3-is-missing-then-utoh-returns-an-error" {
  run env PATH="${BATS_TEST_TMPDIR}" __hhs_utoh f123

  assert_failure
  assert_output --partial 'Missing required dependencies'
  assert_output --partial 'python3'
}
