#!/usr/bin/env bash
if [[ "${HHS_ENCODE_FAIL:-}" == "1" ]]; then
  exit 1
fi
input=""
output=""
while [[ $# -gt 0 ]]; do
  case "$1" in
    -i)
      shift
      input="$1"
      ;;
    -o)
      shift
      output="$1"
      ;;
  esac
  shift
done
[[ -n "$input" && -n "$output" ]] || exit 1
[[ -f "$input" ]] && cp "$input" "$output" || :
exit 0
