#!/usr/bin/env bash

case "$1" in
  --version)
    echo "sample-version 1.0.0"
    exit 0
    ;;
  -v)
    echo "sample-version v1.0.0"
    exit 0
    ;;
  -V)
    echo "sample-version V1.0.0"
    exit 0
    ;;
esac

exit 1
