name: build-and-test
run-name: Build & Test

on:
  workflow_dispatch:
  push:
    branches:
      - '**'
    paths:
      - 'bin/**'
      - 'dotfiles/**'
      - 'tests/**'
      - '*.bash'
  fork:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'
    paths:
      - 'bin/**'
      - 'dotfiles/**'
      - 'tests/**'
      - '*.bash'

permissions:
  contents: write

env:
  JOB_NAME: "HomeSetup-Build"

jobs:
  build:
    strategy:
      matrix:
        os:
          - "ubuntu-latest"
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: ${{ vars.PYTHON_VERSION }}
    - name: Update PIP
      run: pip install --upgrade pip
    - name: Install HomeSetup with Prefix and Test
      run: |
        ./install.bash -r -p "${{ github.workspace }}"
        echo "${{ github.workspace }}" > "${HOME}/.hhs-prefix"
        source "${HOME}"/.bashrc
        __hhs tests
