name: build-and-test
run-name: Build & Test

on:
  workflow_dispatch:
    inputs:
      ubuntu:
        description: 'Build & Test on Ubuntu latest ?'
        default: true
        required: true
        type: boolean
      macos:
        description: 'Build & Test on macOS latest ?'
        default: false
        required: true
        type: boolean
  push:
    branches:
      - '**'
    paths:
      - 'bin/**'
      - 'dotfiles/**'
      - 'tests/**'
      - '*.bash'
  fork:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'
    paths:
      - 'bin/**'
      - 'dotfiles/**'
      - 'tests/**'
      - '*.bash'

permissions:
  contents: write

env:
  JOB_NAME: "HomeSetup-Build"

jobs:
  set-os-matrix:
    runs-on: "ubuntu-latest"
    outputs:
      exclude-array: ${{ steps.set-matrix-items.outputs.excludes }}
    steps:
      - name: Show Selected Input
        run: |
          echo "Build Ubuntu: ${{inputs.ubuntu}}"
          echo " Build macOS: ${{inputs.macos}}"
      - id: set-matrix-items
        run: |
          count=0
          all=('ubuntu-latest' 'macos-latest')
          while read -r next; do
            if [[ (${next} == 'ubuntu-latest' && "false" == "${{inputs.ubuntu}}") ||
                  (${next} == 'macos-latest' && "false" == "${{inputs.macos}}") ]]; then
              item="{\"os\":\"${next}\"},"
              [[ "${JSON}" != *"${item}"* ]] && JSON="${JSON}${item}"
              ((count+=1))
            fi
          done < <(printf '%s\n' "${all[@]}")
          [[ $JSON == *, ]] && JSON="${JSON%?}"
          [[ ${count} -eq ${#all[@]} ]] && JSON="{\"os\":\"macos-latest\"}"
          JSON="[${JSON}]"
          echo "JSON: ${JSON}"
          echo "excludes=$( echo "${JSON}" )" >> $GITHUB_OUTPUT

  build:
    needs: set-os-matrix
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-latest', 'macos-latest']
        exclude: ${{fromJSON(needs.set-os-matrix.outputs.exclude-array) }}
    runs-on: ${{ matrix.os }}
    env:
      HHS_LOG_DIR: '/Users/runner/.hhs/log'
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: ${{ vars.PYTHON_VERSION }}
      - name: Update PIP
        run: pip install --upgrade pip
      - name: Install HomeSetup with Prefix
        run: |
          ./install.bash -r -p "${{ github.workspace }}"
          echo "${{ github.workspace }}" > "${HOME}/.hhs-prefix"
          echo -e "\nInstallation information:"
          echo -e "SHELL: ${SHELL}"
          echo -e " HOME: ${HOME}"
          echo -e " USER: ${USER}\n"
          echo -en "Loading bash profile..."
          if source "${HOME}"/.bashrc; then echo "OK"; else echo "FAILED"; fi
          echo "HHS_LOG_DIR=$(echo ${HHS_LOG_DIR})" >> $GITHUB_ENV
          __hhs tests
      - name: Upload installation logs
        if: ${{ always() }}
        uses: actions/upload-artifact@v3
        with:
          name: "${{ matrix.os }}-install-logs"
          path: "${{ env.HHS_LOG_DIR }}"
      - name: Show installation logs
        if: ${{ failure() }}
        run: |
          cat -n "${{ env.HHS_LOG_DIR }}/install.log"
