name: create-release
run-name: Create Release

on:
  push:
    tags:
      - "v?[0-9]+.[0-9]+.[0-9]+"
      - "v?[0-9]+.[0-9]+.[0-9]+a[0-9]+"
      - "v?[0-9]+.[0-9]+.[0-9]+b[0-9]+"
      - "v?[0-9]+.[0-9]+.[0-9]+rc[0-9]+"

  workflow_dispatch:
    inputs:
      tag-name:
        description: 'Release Tag name (default to latest)'
        required: false
        type: string

permissions:
  contents: write

jobs:
  details:
    runs-on: ubuntu-latest
    outputs:
      tag_name: ${{ steps.release.outputs.tag_name }}
    steps:
      - uses: actions/checkout@v4
      - name: Extract tag and Details
        id: release
        run: |
          if [[ "${GITHUB_REF_TYPE}" == "tag" ]]; then
            TAG_NAME="${GITHUB_REF#refs/tags/}"
          elif [[ -n "${{ inputs.tag-name }}" ]]; then
            TAG_NAME="${{ inputs.tag-name }}"
          fi
          echo "TAG_NAME: ${TAG_NAME}" >> $GITHUB_STEP_SUMMARY
          echo "tag_name=$(echo "${TAG_NAME}")" >> "$GITHUB_OUTPUT"

  github_release:
    name: Create GitHub Release
    needs: details
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ needs.details.outputs.tag_name }}
      - name: Create Changelog
        id: change-log
        uses: yorevs/hspylib/.github/actions/changelog@master
        with:
          tag-name: ${{ needs.details.outputs.tag_name }}
      - name: Create GitHub Release
        id: create_release
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          echo "${{ steps.change-log.outputs.changelog }}" > changelog
          gh release create "${{ needs.details.outputs.tag_name }}" --title "${{ vars.APP_NAME }}-${{ needs.details.outputs.tag_name }}-rc${{ github.run_number }}" --notes-file changelog "assets/fonts/Droid-Sans-Mono-for-Powerline-Nerd-Font-Complete.otf"
