name: create-release
run-name: Create Release

on:
  push:
    tags:
      - "v?[0-9]+.[0-9]+.[0-9]+"
      - "v?[0-9]+.[0-9]+.[0-9]+a[0-9]+"
      - "v?[0-9]+.[0-9]+.[0-9]+b[0-9]+"
      - "v?[0-9]+.[0-9]+.[0-9]+rc[0-9]+"

permissions:
  contents: write

jobs:
  details:
    runs-on: ubuntu-latest
    outputs:
      new_version: ${{ steps.release.outputs.new_version }}
      suffix: ${{ steps.release.outputs.suffix }}
      tag_name: ${{ steps.release.outputs.tag_name }}
    steps:
      - uses: actions/checkout@v4
      - name: Extract tag and Details
        id: release
        run: |
          if [[ "${GITHUB_REF_TYPE}" == "tag" ]]; then
            TAG_NAME="${GITHUB_REF#refs/tags/}"
          else
            echo "No tags found!"
            exit 1
          fi
          NEW_VERSION=$(echo $TAG_NAME | awk -F'-' '{print $1}')
          SUFFIX=$(echo $TAG_NAME | grep -oP '[a-z]+[0-9]+' || echo "")
          echo "new_version=$NEW_VERSION" >> "$GITHUB_OUTPUT"
          echo "suffix=$SUFFIX" >> "$GITHUB_OUTPUT"
          echo "tag_name=$TAG_NAME" >> "$GITHUB_OUTPUT"
          echo "New Version is $NEW_VERSION" >> $GITHUB_STEP_SUMMARY
          echo "Suffix is $SUFFIX" >> $GITHUB_STEP_SUMMARY
          echo "Tag name is $TAG_NAME" >> $GITHUB_STEP_SUMMARY

  github_release:
    name: Create GitHub Release
    needs: details
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Create Changelog
        id: change-log
        uses: yorevs/hspylib/.github/actions/changelog@master
        with:
          tag-name: "v${{ needs.details.outputs.tag_name }}"
      - name: Create GitHub Release
        id: create_release
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh release create ${{ needs.details.outputs.tag_name }} dist/* --title "${{ vars.PACKAGE_NAME }}-${{ needs.details.outputs.tag_name }}-rc${{ github.run_number }}" --generate-notes

  build-docker-images:
    name: Create Docker Hub Images
    needs: details
    uses: yorevs/homesetup/.github/workflows/docker-deploy.yml@master
    with:
      image_tag: ${{ needs.publish.outputs.version }}
    secrets: inherit
