name: docker-deploy
run-name: Build & Push Docker Images

on:
  workflow_dispatch:
    inputs:
      gradle_debug_params:
        description: 'Gradle debug parameters'
        default: ''
        required: false
        type: string
      image_tag:
        description: 'Docker Image Tag'
        default: 'latest'
        required: true
        type: string

  workflow_call:
    inputs:
      image_tag:
        description: 'Docker Image Tag'
        default: 'latest'
        required: true
        type: string

permissions:
  contents: read

jobs:

  build-docker-images:
    strategy:
      matrix:
        os:
          - "ubuntu-latest"
        docker-container:
          - "ubuntu"
          - "fedora"
          - "centos"
          - "alpine"
    runs-on: ${{ matrix.os }}
    environment: homesetup
    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: ${{ vars.PYTHON_VERSION }}
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          context: "docker/${{ matrix.docker-container }}"
          file: "docker/${{ matrix.docker-container }}/Dockerfile"
          push: true
          tags: "${{ env.DOCKERHUB_USERNAME }}/hhs-${{ matrix.docker-container }}:${{ inputs.image_tag }}"
