name: docker-deploy
run-name: Build & Push Docker Images

on:
  workflow_dispatch:
    inputs:
      gradle_debug_params:
        description: 'Gradle debug parameters'
        default: ''
        required: false
        type: string
      image_tag:
        description: 'Docker Image Tag'
        default: 'latest'
        required: true
        type: string

  workflow_call:
    inputs:
      image_tag:
        description: 'Docker Image Tag'
        default: ''
        required: true
        type: string

permissions:
  contents: read

jobs:

  detect-version:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v3
      - name: Detect Version
        id: detect-version
        run: |
          appVersion=$(grep -e '^[0-9]+\.[0-9]+\.[0-9]+' "${{ github.workspace }}/.VERSION")
          echo "Application version: ${appVersion}"
          echo路"app_version=$(echo路$appVersion)"路>>路$GITHUB_OUTPUT
    outputs:
      app_version: ${{ steps.detect-version.outputs.app_version }}

  build-docker-images:
    needs: detect-version
    strategy:
      matrix:
        os:
          - "ubuntu-latest"
        docker-container:
          - "ubuntu"
          - "fedora"
          - "centos"
          - "alpine"
    runs-on: ${{ matrix.os }}
    environment: homesetup
    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      IMAGE_TAG: ${{ inputs.image_tag || needs.detect-version.outputs.app_version }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: ${{ vars.PYTHON_VERSION }}
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          context: "docker/${{ matrix.docker-container }}"
          file: "docker/${{ matrix.docker-container }}/Dockerfile"
          push: true
          tags: "${{ env.DOCKERHUB_USERNAME }}/hhs-${{ matrix.docker-container }}:${{ env.IMAGE_TAG }}"
