name: install-activate-test
run-name: HomeSetup install-activate-test [@${{ github.actor }}]

on:
  workflow_dispatch:
  push:
    branches:
      - '**'
    paths:
      - 'bin/**'
      - 'dotfiles/**'
      - 'tests/**'
      - '*.bash'
  fork:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'
    paths:
      - 'bin/**'
      - 'dotfiles/**'
      - 'tests/**'
      - '*.bash'

permissions:
  contents: write

env:
  JOB_NAME: "HomeSetup-install-activate-test"

jobs:
  build:
    strategy:
      matrix:
        os: [ "ubuntu-latest" ]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - name: Setup BATS
      uses: mig4/setup-bats@v1
      with:
        bats-version: '1.10.0'
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - name: Update PIP
      run: pip install --upgrade pip
    - name: Install HomeSetup with Prefix and Test
      run: |
        ./install.bash -r -p "${{ github.workspace }}"
        echo "${{ github.workspace }}" > "${HOME}/.hhs-prefix"
        source "${HOME}"/.bashrc
        __hhs tests
    - name: Commit badges
      run: |
        git config --global user.name "$(git log -n 1 --pretty=format:%an)"
        git config --global user.email "$(git log -n 1 --pretty=format:%ae)"
        if [[ -z $(git status --porcelain) ]]; then
          echo 'Build/Check badges are the same, skipping commit.'
        else
          git add '*-badge.svg'
          git commit -m "[@${{ github.actor }}] AUTO updated build & check badges"
          git push origin HEAD
        fi
