name: publish-revision

on:
  workflow_dispatch:
    inputs:
      gradle_debug_params:
        description: 'Gradle debug parameters'
        default: ''
        required: false
        type: string
      comment:
        description: 'Publish description'
        default: 'No description'
        required: false
        type: string
      tag_version:
        description: 'Whether tho tag this version or not'
        type: boolean
        required: true
        default: false
      is_major:
        description: 'Whether this version is major or not'
        type: boolean
        required: true
        default: false

permissions:
  contents: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 11
    - uses: gradle/gradle-build-action@v2
      with:
        gradle-version: '7.4'
    - uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - name: Install Python tools
      run: |
        pip install --upgrade pip
        pip install --upgrade bumpver
    - name: Fetch revision details
      run: |
        git fetch --prune --unshallow
        echo "Publishing new HomeSetup revision"
        echo "New HomeSetup Revision: ${{ inputs.comment }}" > '.changelog.txt'
        echo "Changelog: " >> '.changelog.txt'
        echo "------------------------------------------------------------" >> '.changelog.txt'
        ./gradlew changelog ${gradle_debug_params} | grep -E "^'[0-9a-z]{7}" | sed -r "s/^'|'$/  /g" >> '.changelog.txt'
    - name: Create a changelog
      run: |
        cat '.changelog.txt'
        git config --global user.name "$(git log -n 1 --pretty=format:%an)"
        git config --global user.email "$(git log -n 1 --pretty=format:%ae)"
        git add '.changelog.txt'
        git commit -m "${{ inputs.comment }}"
    - name: Update major number
      if: ${{ inputs.is_major }}
      run: |
        ./gradlew updateMinor ${gradle_debug_params}
    - name: Publish and tag revision
      run: |
        ./gradlew publish ${gradle_debug_params} -Ptag="${{ inputs.tag_version }}"
