name: publish-revision

on:
  workflow_dispatch:
    inputs:
      comment:
        description: 'Publish description'
        default: ''
        required: false
        type: string
      gradle_debug_params:
        description: 'Gradle debug parameters'
        default: ''
        required: false
        type: string

permissions:
  contents: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 11
    - uses: gradle/gradle-build-action@v2
      with:
        gradle-version: 7.4

    - name: Publish new version
      run: |
        git fetch --prune --unshallow
        echo "Publishing new HomeSetup revision"
        echo '' >> .changelog.txt
        echo "New HomeSetup Revision: ${{ inputs.comment }}" >> .changelog.txt
        echo "Changelog: " >> .changelog.txt
        echo "------------------------------------------------------------" >> .changelog.txt
        ./gradlew changelog | grep -E "^'[0-9a-z]{7}" | sed -r "s/^'|'$/  /g" >> .changelog.txt
        cat .changelog.txt
        git config --global user.name 'Hugo Saporetti Junior'
        git config --global user.email 'yorevs@gmail.com'
        git add .changelog.txt
        git commit -F .changelog.txt
        git push origin HEAD
        ./gradlew publish
