name: publish-revision
run-name: HomeSetup publish-revision [@${{ github.actor }}]

on:
  workflow_dispatch:
    inputs:
      gradle_debug_params:
        description: 'Gradle debug parameters'
        default: ''
        required: false
        type: string
      comment:
        description: 'Publish description'
        default: 'New HomeSetup '
        required: false
        type: string
      tag_version:
        description: 'Tag this version ?'
        type: boolean
        required: true
        default: false
      release_type:
        description: 'Major/Minor or Patch only update ?'
        type: choice
        required: true
        default: 'patch'
        options:
          - 'patch'
          - 'minor'
          - 'major'

permissions:
  contents: write

jobs:
  publish:
    strategy:
      matrix:
        os: [ "ubuntu-latest" ]
        docker-container: ["ubuntu", "fedora", "centos", "alpine"]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 11
    - uses: gradle/gradle-build-action@v2
      with:
        gradle-version: '7.4'
    - uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - name: Install Python tools
      run: |
        pip install --upgrade pip
        pip install --upgrade bumpver

    - name: Fetch revision details
      run: |
        git fetch --prune --unshallow
        echo "Publishing new HomeSetup revision"
        echo "New HomeSetup Revision: ${{ inputs.comment }}" > '.changelog.txt'
        echo "Changelog: " >> '.changelog.txt'
        echo "------------------------------------------------------------" >> '.changelog.txt'
        ./gradlew changelog ${gradle_debug_params} | grep -E "^'[0-9a-z]{7}" | sed -r "s/^'|'$/  /g" >> '.changelog.txt'

    - name: Create changelog file
      run: |
        cat '.changelog.txt'
        git config --global user.name "$(git log -n 1 --pretty=format:%an)"
        git config --global user.email "$(git log -n 1 --pretty=format:%ae)"
        git add '.changelog.txt'
        git commit -m "[@${{ github.actor }}] ${{ inputs.comment }}"

    - name: Update minor number
      if: ${{ inputs.release_type == 'minor' }}
      run: ./gradlew updateMinor ${gradle_debug_params}

    - name: Update major number
      if: ${{ inputs.release_type == 'major' }}
      run: ./gradlew updateMajor ${gradle_debug_params}

    - name: Publish and tag revision
      run: |
        ./gradlew publish ${gradle_debug_params} -Ptag="${{ inputs.tag_version }}"

  build-images:
    needs: publish
    runs-on: ${{ matrix.os }}
    environment: homesetup
    steps:
    - uses: actions/checkout@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ envs.DOCKERHUB_USERNAME }}
        password: ${{ envs.DOCKERHUB_TOKEN }}
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: "docker/${{ docker-container }}"
        file: "docker/${{ docker-container }}/Dockerfile"
        push: true
        tags: "${{ envs.DOCKERHUB_USERNAME }}/hhs-${{ docker-container }}:latest"
